#!/bin/bash
# Script to start rover scripts

echo "Running rover scripts as daemon..."

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# reset logs
echo " " > $DIR/stdout.log
echo " " > $DIR/stderr.log


#set full volume
amixer set PCM 100%

#this is forever daemon startup
sudo $DIR/../node_modules/forever/bin/forever -o stdout.log -e stderr.log start $DIR/../bin/rover/control.js deploy -debug -1 nogps

#this is regular node startup
#sudo -u $USER  /home/pi/nodejs/rover/node.sh /home/pi/nodejs/rover/bin/rover/control.js deploy -debug -1
