#!/bin/bash
# Script to start rover scripts
USER=pi
echo "Running rover scripts as daemon..."

#this is forever daemon startup
sudo -u $USER /home/pi/nodejs/rover/node_modules/forever/bin/forever start /home/pi/nodejs/rover/bin/rover/control.js deploy -debug 5

#this is regular node startup
#sudo -u $USER  /home/pi/nodejs/rover/node.sh /home/pi/nodejs/rover/bin/rover/control.js deploy -debug -1
