#!/bin/bash
# Script to start application
echo "Doing autorun script..."
cd /home/pi/nodejs/rover
sudo git pull origin master
cd
sudo /home/pi/nodejs/rover/node_modules/forever/bin/forever start /home/pi/nodejs/rover/bin/rover/control.js deploy 
