#!/bin/bash

# shell/installers/ffmpeg-rpi
# configure ffmpeg for rpi
# ffmpeg must already be installed.

echo "-----Compiling ffmpeg for RPi-----"
echo "deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi" > /etc/apt/sources.list
echo "deb-src http://www.deb-multimedia.org sid main" >> /etc/apt/sources.list
echo "deb http://www.deb-multimedia.org wheezy main non-free" >> /etc/apt/sources.list
apt-get update
apt-get install deb-multimedia-keyring
sudo apt-get source ffmpeg-dmo
DMO_DIR=`ls | grep ffmpeg-dmo`
cd $DMO_DIR
./configure
sudo make && make install

